name: Deploy to Digital Ocean
on:
  push:
    branches: [ master ]
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
      - uses: appleboy/ssh-action@master
        with:
            host: "prod.bezi.io"
            username: ${{ secrets.DEPLOY_USERNAME }}
            password: ${{ secrets.DEPLOY_PASSWORD }}
            script: "(cd /opt/github/bezi.io/ && ./deploy.sh)"
